# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Pg-Pcurse
version:      0.01
version_from: lib/Pg/Pcurse.pm
installdirs:  site
requires:
    Carp::Assert:                  0
    Curses:                        0
    Curses::Widgets:               0
    Getopt::Compact:               0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
