--- #YAML:1.0
name:                Pg-Pcurse
version:             0.06
abstract:            Monitors a Postgres cluster
license:             ~
author:              
    - Ioannis Tambouras <ioannis@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Carp::Assert:                  0
    Curses:                        0
    Curses::Widgets:               0
    Data::Dumper:                  0
    DBIx::Abstract:                0
    Getopt::Compact:               0
    Test::Pod:                     1.0
    Test::Pod::Coverage:           1.0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
