---
name: Pg-Pcurse
version: 0.22
author:
  - Ioannis Tambouras<ioannis@cpan.org>
abstract: Monitors a Postgres cluster
license: gpl
requires:
  Carp::Assert: 0.18
  Curses: 1.23
  Curses::Widgets: 1.997
  DBIx::Abstract: 1.006
  Data::Dumper: 2.121_08
  File::Slurp: 9999.12
  Getopt::Long: 2.35
  User::pwent: 1.00
  perl: 5.008
recommends:
  Test::Pod: 1
  Test::Pod::Coverage: 1.0
provides:
  Pg::Pcurse:
    file: lib/Pg/Pcurse.pm
    version: 0.13
  Pg::Pcurse::Misc:
    file: lib/Pg/Pcurse/Misc.pm
    version: 0.08
  Pg::Pcurse::Query0:
    file: lib/Pg/Pcurse/Query0.pm
    version: 0.12
  Pg::Pcurse::Query1:
    file: lib/Pg/Pcurse/Query1.pm
    version: 0.12
  Pg::Pcurse::Query2:
    file: lib/Pg/Pcurse/Query2.pm
    version: 0.12
  Pg::Pcurse::Query3:
    file: lib/Pg/Pcurse/Query3.pm
    version: 0.12
  Pg::Pcurse::Widget:
    file: lib/Pg/Pcurse/Widget.pm
    version: 0.12
generated_by: Module::Build version 0.2611
